version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - HOST=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
      - WATCHPACK_POLLING=true   # hot reload más fiable en Docker
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_ISSUER=${JWT_ISSUER}
      - JWT_AUDIENCE=${JWT_AUDIENCE}
      - JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
    volumes:
      - ./:/app                  # tu código con hot reload
      - node_modules:/app/node_modules  # preserva deps del contenedor

volumes:
  node_modules:
