services:
  dev:
    image: node:20-alpine
    working_dir: /app
    # Monta tu c√≥digo dentro del contenedor
    volumes:
      - ./:/app
      - /app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      - HOST=0.0.0.0
      - CHOKIDAR_USEPOLLING=true   # ayuda con hot-reload dentro de Docker
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"                # Next por defecto
    profiles: ["dev"]

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    ports:
      - "3000:3000"
    profiles: ["prod"]

